language: generic
matrix:
   include:
      - os: linux
        dist: trusty
        sudo: required
      - os: osx
        osx_image: xcode9.2
addons:
  apt:
    packages:
    - clang
    - pkg-config
env:
  - SWIFT_VERSION=swift-4.1-RELEASE
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then SWIFT_DIR=tests ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir $SWIFT_DIR ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl https://swift.org/builds/swift-4.1-release/ubuntu1404/swift-4.1-RELEASE/swift-4.1-RELEASE-ubuntu14.04.tar.gz -s | tar xz -C $SWIFT_DIR &> /dev/null ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install clang libicu-dev ; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$(pwd)/tests/$SWIFT_VERSION-ubuntu14.04/usr/bin:"${PATH}" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swift test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild clean test -scheme Promise -destination 'platform=iOS Simulator,name=iPhone SE,OS=latest' ; fi

